from flask import Blueprint, jsonify
from datetime import datetime
import src.models.ml_model as state

report_bp = Blueprint('report', __name__)


@report_bp.route('/download_results', methods=['POST'])
def download_results():
    if state.model is None:
        return jsonify({'success': False, 'error': 'No model trained'}), 400

    try:
        report = f"""SP-105 AIML EXPLAINER - ANALYSIS REPORT
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
================================================

MODEL INFORMATION:
- Model Type: Random Forest Classifier
- Training Samples: {len(state.X_train)}
- Test Samples: {len(state.X_test)}
- Number of Features: {len(state.feature_names)}
- Model Accuracy: {state.model.score(state.X_test, state.y_test):.4f}

FEATURES: {', '.join(state.feature_names)}

DATASET: {state.dataset_info.get('filename', 'Iris (sample)') if state.dataset_info else 'Iris (sample)'}

================================================
Generated by SP-105 AIML Explainer
Kennesaw State University - Fall 2025
"""
        filename = f"analysis_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
        return jsonify({'success': True, 'report': report, 'filename': filename})

    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500